### ISSUE TITLE
Racialist parameter

### ISSUE THREAD

**Issue by ChloeTigre** [woodnathan/dicks#3]
Hello,

Could you please remove the "European", "Asian", "African" "features". This is just a reproduction of racist stereotypes and it's IMO contrary to the spirit of open source.

Thanks

**Comment by woodnathan** [comment]
Hi ChloeTigre,

If you had looked at this Ruby Gem you would notice that this is a thin library for interacting with an API written by someone else entirely. All features of the service were implemented by them.
